"""Add rider revenue and finance models

Revision ID: 339d19f0163e
Revises: 9a058d519f41
Create Date: 2026-01-03 20:15:27.799497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339d19f0163e'
down_revision = '9a058d519f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rider_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rider_earnings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=True))
        batch_op.create_unique_constraint('uq_orders_tracking_id', ['tracking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('rider_earnings')

    # ### end Alembic commands ###
