"""Add LaundryItem model

Revision ID: 9a058d519f41
Revises: 77cfb2238254
Create Date: 2026-01-02 16:24:21.836185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a058d519f41'
down_revision = '77cfb2238254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laundry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('price_wash', sa.Float(), nullable=True),
    sa.Column('price_dryclean', sa.Float(), nullable=True),
    sa.Column('price_iron', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laundry_items')
    # ### end Alembic commands ###
